### ISSUE TITLE
Environmental Variables with Rails?

### ISSUE THREAD

**Issue by sdegennaro** [sdegennaro/Project4_DoFunStuff#1]
I'm trying to make an api call with a key in my rails app, but am not sure how to hide the key. Internet says to use the Figaro gem?

**Comment by rapala61** [comment]
Have you given `dotenv` a shot? https://github.com/bkeepers/dotenv

**Comment by rapala61** [comment]
This is a good read too: https://launchschool.com/blog/managing-environment-configuration-variables-in-rails
